#! /usr/bin/env python
#
# Support module generated by PAGE version 4.6
# In conjunction with Tcl version 8.6
#    Feb 10, 2016 09:16:47 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import called

#p_dict_1 = {'geom': "+200+650", 'instance': 1, 'color' : 'firebrick'}
#p_dict_2 = {'geom': "+1000+650", 'instance': 2, 'color' : 'plum'}


def open_two():
    print "open_two starts"
    called.create_Called(root, color="firebrick",
                         instance=1, geom= "+200+650")
    called.create_Called(root, color="plum", instance=2, geom="+1000+650")


def quit():
    sys.exit()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import main
    main.vp_start_gui()


